### ISSUE TITLE
nrf52dk bootloader

### ISSUE THREAD

**Issue by drahnr** [tock/tock-bootloader#3]
What is necessary to use the bootloader with the `nrf52dk` USB debugger?

**Comment by alevy** [comment]
You can currently use `tockloader` without the bootloader, since it has a `--jtag` options which simply uses `JLinkExe` instead of the bootloader over UART. I think `make TOCK_BOARD=nrf52dk flash` does this from within the Tock repository right now (both apps and kernel).

@bradjc is working on an implementation of the bootloader in Tock (it currently uses Atmel's SDK) that would also require the NVRAM controller to be supported on the NRF52.

Sort of a duplicate of helena-project/tock#544

**Comment by drahnr** [comment]
`tockloader install --jtag --board nrf52dk --arch cortex-m4` (no bootloader needed, just for sake of completeness)
